# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  
  couchdb1org1:
    container_name: couchdb1org1
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"

  peer1.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1org1:5984
    depends_on:
      - couchdb1org1

